blueprint:
  name: "Maint Reset Task (v0.5.3)"
  description: "Reset the last completed date of maintenance tasks."
  domain: automation
  input:
    tag:
      name: "Tag"
      description: "The NFC tag ID to trigger the reset."
      selector:
        text:
    task:
      name: "Task"
      description: "The binary sensor for the target task."
      selector:
        entity:
          domain: binary_sensor
          integration: maint
    task2:
      name: "Task2"
      description: "dsadsa."
      selector:
        text:

triggers:
  - trigger: event
    event_type: tag_scanned

conditions:
  - condition: template
    value_template: "{{ trigger.event.data.tag_id == tag }}"

actions:
  - variables:
      tag: !input tag
      task: !input task
  - action: logbook.log
    data_template:
      name: custom.automation
      message: |
        Resetting {{ task }} beacuse tag {{ tag }} was scanned
  - repeat:
      for_each: '{{ task }}'
      sequence:
        - action: maint.reset_last_completed
          data:
            entity_id: "{{ repeat.item }}"
