---
name: "Question"
description: "Ask a question about the integration"
body:
- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing questions to see if its already been asked.

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: This issue is not a duplicate issue of any [previous issues](https://github.com/chrisdoherty4/maint/issues?q=is%3Aissue+label%3A%22Question%22+)..
        required: true

- type: textarea
  attributes:
    label: "What is your question?"
    description: "A clear and concise description of what you need help with."
  validations:
    required: true

